version: "3"
services:
  frps:
    # replace username/repo:tag with your name and image details
    image: vpcdata/frpsrv:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - host
